server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://192.168.147.128:5432/laboratory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        default_batch_fetch_size: 100
        jdbc_batch_size: 50
        jdbc_fetch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: 192.168.147.128:9092
    consumer:
      group-id: otp-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
          spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          spring.json.trusted.packages: org.mos.uaa.kafka
    producer:
      retries: 3
      acks: all
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: 192.168.147.128
      port: 6379

  jackson:
    default-property-inclusion: non_null

  threads:
    virtual:
      enabled: true

otp:
  expired-time: 180
  resend-delay: 120
  max-attempt: 5
